// Initial data for the application

// Initial user data
const initialUser = {
  totalInvestment: 5800,
  totalEarnings: 1250,
  investmentChange: 350,
  earningsChange: 120,
  projectsAdded: 5,
  totalProjects: 21,
  tasksCompleted: 12,
  totalTasks: 18
};

// Initial projects data
const initialProjects = [
  {
    id: '1',
    name: 'Blockmesh',
    description: 'Decentralized mesh network with fast finality',
    category: 'Layer 2',
    logo: 'assets/logos/blockmesh.svg',
    gradientFrom: '#6366F1',
    gradientTo: '#8B5CF6',
    borderColor: '#6366F1',
    performance: 18.5,
    funding: '$32M',
    reward: '1000 BMT',
    tgeDate: 'June 15, 2024',
    type: 'Testnet',
    tags: ['L2', 'Infrastructure', 'Fast Finality'],
    isFavorite: false,
    isAdded: false
  },
  {
    id: '2',
    name: 'Taker',
    description: 'Decentralized order book DEX with cross-chain capabilities',
    category: 'DeFi',
    logo: 'assets/logos/taker.svg',
    gradientFrom: '#10B981',
    gradientTo: '#059669',
    borderColor: '#10B981',
    performance: 24.2,
    funding: '$15M',
    reward: '5000 TKR',
    tgeDate: 'July 20, 2024',
    type: 'Testnet',
    tags: ['DEX', 'Cross-chain', 'Order Book'],
    isFavorite: true,
    isAdded: true
  },
  {
    id: '3',
    name: 'Bless',
    description: 'AI-powered prediction market and betting platform',
    category: 'GameFi',
    logo: 'assets/logos/bless.svg',
    gradientFrom: '#F59E0B',
    gradientTo: '#D97706',
    borderColor: '#F59E0B',
    performance: 15.8,
    funding: '$8.5M',
    reward: '1500 BLS',
    tgeDate: 'August 5, 2024',
    type: 'Mainnet',
    tags: ['AI', 'Prediction', 'Betting'],
    isFavorite: false,
    isAdded: true
  },
  {
    id: '4',
    name: 'Hyperdrive',
    description: 'High-throughput blockchain for enterprise applications',
    category: 'Infrastructure',
    logo: 'assets/logos/hyperdrive.svg',
    gradientFrom: '#EC4899',
    gradientTo: '#BE185D',
    borderColor: '#EC4899',
    performance: 31.0,
    funding: '$45M',
    reward: '2000 HDV',
    tgeDate: 'May 10, 2024',
    type: 'Mainnet',
    tags: ['Enterprise', 'Scalability', 'High-throughput'],
    isFavorite: true,
    isAdded: true
  },
  {
    id: '5',
    name: 'Alchemy',
    description: 'Decentralized asset management protocol',
    category: 'DeFi',
    logo: 'assets/logos/alchemy.svg',
    gradientFrom: '#8B5CF6',
    gradientTo: '#7C3AED',
    borderColor: '#8B5CF6',
    performance: 19.5,
    funding: '$22M',
    reward: '3500 ALK',
    tgeDate: 'September 1, 2024',
    type: 'Testnet',
    tags: ['Asset Management', 'DeFi', 'Yield'],
    isFavorite: false,
    isAdded: true
  },
  {
    id: '6',
    name: 'Vortex',
    description: 'Decentralized cloud computing marketplace',
    category: 'Infrastructure',
    logo: 'assets/logos/vortex.svg',
    gradientFrom: '#3B82F6',
    gradientTo: '#2563EB',
    borderColor: '#3B82F6',
    performance: 28.7,
    funding: '$37M',
    reward: '4000 VTX',
    tgeDate: 'July 8, 2024',
    type: 'Mainnet',
    tags: ['Cloud', 'Compute', 'Marketplace'],
    isFavorite: false,
    isAdded: false
  },
  {
    id: '7',
    name: 'Axion',
    description: 'Real-world asset tokenization platform',
    category: 'DeFi',
    logo: 'assets/logos/axion.svg',
    gradientFrom: '#FB7185',
    gradientTo: '#E11D48',
    borderColor: '#FB7185',
    performance: 22.3,
    funding: '$18M',
    reward: '2500 AXN',
    tgeDate: 'August 22, 2024',
    type: 'Testnet',
    tags: ['RWA', 'Tokenization', 'DeFi'],
    isFavorite: false,
    isAdded: false
  },
  {
    id: '8',
    name: 'Nebula',
    description: 'Cross-chain NFT marketplace and creator platform',
    category: 'NFT',
    logo: 'assets/logos/nebula.svg',
    gradientFrom: '#6366F1',
    gradientTo: '#4F46E5',
    borderColor: '#6366F1',
    performance: 16.9,
    funding: '$12M',
    reward: '3000 NBL',
    tgeDate: 'June 30, 2024',
    type: 'Mainnet',
    tags: ['NFT', 'Creator', 'Marketplace'],
    isFavorite: false,
    isAdded: false
  },
  {
    id: '9',
    name: 'Quantum',
    description: 'Privacy-focused L2 with zero-knowledge proofs',
    category: 'Layer 2',
    logo: 'assets/logos/quantum.svg',
    gradientFrom: '#10B981',
    gradientTo: '#059669',
    borderColor: '#10B981',
    performance: 27.1,
    funding: '$40M',
    reward: '1800 QTM',
    tgeDate: 'May 25, 2024',
    type: 'Testnet',
    tags: ['Privacy', 'ZK-Proofs', 'L2'],
    isFavorite: false,
    isAdded: false
  },
  {
    id: '10',
    name: 'Zephyr',
    description: 'Decentralized social media platform with token rewards',
    category: 'Social',
    logo: 'assets/logos/zephyr.svg',
    gradientFrom: '#F59E0B',
    gradientTo: '#D97706',
    borderColor: '#F59E0B',
    performance: 14.2,
    funding: '$9M',
    reward: '5000 ZPH',
    tgeDate: 'September 15, 2024',
    type: 'Mainnet',
    tags: ['Social', 'Content', 'Rewards'],
    isFavorite: false,
    isAdded: true
  },
  {
    id: '11',
    name: 'Fusion',
    description: 'Interoperability protocol connecting all blockchains',
    category: 'Infrastructure',
    logo: 'assets/logos/fusion.svg',
    gradientFrom: '#EC4899',
    gradientTo: '#BE185D',
    borderColor: '#EC4899',
    performance: 33.5,
    funding: '$50M',
    reward: '2200 FSN',
    tgeDate: 'July 1, 2024',
    type: 'Testnet',
    tags: ['Interoperability', 'Cross-chain', 'Bridge'],
    isFavorite: false,
    isAdded: false
  },
  {
    id: '12',
    name: 'Polaris',
    description: 'GameFi platform for Web3 game development and distribution',
    category: 'GameFi',
    logo: 'assets/logos/polaris.svg',
    gradientFrom: '#8B5CF6',
    gradientTo: '#7C3AED',
    borderColor: '#8B5CF6',
    performance: 21.7,
    funding: '$25M',
    reward: '3200 POL',
    tgeDate: 'August 10, 2024',
    type: 'Mainnet',
    tags: ['Gaming', 'Development', 'Distribution'],
    isFavorite: false,
    isAdded: false
  },
  {
    id: '13',
    name: 'Solstice',
    description: 'Decentralized identity and reputation system',
    category: 'Identity',
    logo: 'assets/logos/solstice.svg',
    gradientFrom: '#3B82F6',
    gradientTo: '#2563EB',
    borderColor: '#3B82F6',
    performance: 18.9,
    funding: '$14M',
    reward: '2800 SOL',
    tgeDate: 'June 20, 2024',
    type: 'Testnet',
    tags: ['Identity', 'Reputation', 'DAO'],
    isFavorite: false,
    isAdded: false
  },
  {
    id: '14',
    name: 'Horizon',
    description: 'Decentralized storage network with AI data processing',
    category: 'Storage',
    logo: 'assets/logos/horizon.svg',
    gradientFrom: '#FB7185',
    gradientTo: '#E11D48',
    borderColor: '#FB7185',
    performance: 25.3,
    funding: '$30M',
    reward: '4000 HRZ',
    tgeDate: 'May 15, 2024',
    type: 'Mainnet',
    tags: ['Storage', 'AI', 'Processing'],
    isFavorite: false,
    isAdded: false
  },
  {
    id: '15',
    name: 'Nova',
    description: 'High-performance blockchain for scientific computing',
    category: 'Infrastructure',
    logo: 'assets/logos/nova.svg',
    gradientFrom: '#6366F1',
    gradientTo: '#4F46E5',
    borderColor: '#6366F1',
    performance: 29.8,
    funding: '$42M',
    reward: '1500 NOV',
    tgeDate: 'July 25, 2024',
    type: 'Testnet',
    tags: ['Scientific', 'Computing', 'Performance'],
    isFavorite: false,
    isAdded: false
  },
  {
    id: '16',
    name: 'Eclipse',
    description: 'Zero-knowledge payment solution for e-commerce',
    category: 'Payments',
    logo: 'assets/logos/eclipse.svg',
    gradientFrom: '#10B981',
    gradientTo: '#059669',
    borderColor: '#10B981',
    performance: 23.6,
    funding: '$20M',
    reward: '3500 ECL',
    tgeDate: 'August 15, 2024',
    type: 'Mainnet',
    tags: ['Payments', 'E-commerce', 'ZK'],
    isFavorite: false,
    isAdded: false
  },
  {
    id: '17',
    name: 'Orion',
    description: 'Decentralized gaming platform with play-to-earn mechanics',
    category: 'GameFi',
    logo: 'assets/logos/orion.svg',
    gradientFrom: '#F59E0B',
    gradientTo: '#D97706',
    borderColor: '#F59E0B',
    performance: 17.2,
    funding: '$11M',
    reward: '5000 ORN',
    tgeDate: 'September 5, 2024',
    type: 'Testnet',
    tags: ['Gaming', 'P2E', 'Metaverse'],
    isFavorite: false,
    isAdded: false
  },
  {
    id: '18',
    name: 'Pulse',
    description: 'DeFi lending protocol with dynamic interest rates',
    category: 'DeFi',
    logo: 'assets/logos/pulse.svg',
    gradientFrom: '#EC4899',
    gradientTo: '#BE185D',
    borderColor: '#EC4899',
    performance: 20.9,
    funding: '$16M',
    reward: '2000 PLS',
    tgeDate: 'June 10, 2024',
    type: 'Mainnet',
    tags: ['Lending', 'Interest', 'DeFi'],
    isFavorite: false,
    isAdded: false
  },
  {
    id: '19',
    name: 'Genesis',
    description: 'Decentralized autonomous organization platform',
    category: 'DAO',
    logo: 'assets/logos/genesis.svg',
    gradientFrom: '#8B5CF6',
    gradientTo: '#7C3AED',
    borderColor: '#8B5CF6',
    performance: 19.4,
    funding: '$15M',
    reward: '4000 GNS',
    tgeDate: 'July 15, 2024',
    type: 'Testnet',
    tags: ['DAO', 'Governance', 'Voting'],
    isFavorite: false,
    isAdded: false
  },
  {
    id: '20',
    name: 'Phoenix',
    description: 'Decentralized derivatives exchange with on-chain settlement',
    category: 'DeFi',
    logo: 'assets/logos/phoenix.svg',
    gradientFrom: '#3B82F6',
    gradientTo: '#2563EB',
    borderColor: '#3B82F6',
    performance: 26.5,
    funding: '$35M',
    reward: '3000 PHX',
    tgeDate: 'August 1, 2024',
    type: 'Mainnet',
    tags: ['Derivatives', 'Trading', 'Settlement'],
    isFavorite: false,
    isAdded: false
  },
  {
    id: '21',
    name: 'Velocity',
    description: 'High-frequency trading protocol with minimal slippage',
    category: 'DeFi',
    logo: 'assets/logos/velocity.svg',
    gradientFrom: '#FB7185',
    gradientTo: '#E11D48',
    borderColor: '#FB7185',
    performance: 30.2,
    funding: '$28M',
    reward: '2500 VEL',
    tgeDate: 'May 30, 2024',
    type: 'Testnet',
    tags: ['Trading', 'HFT', 'Slippage'],
    isFavorite: false,
    isAdded: false
  }
];

// Initial tasks data
const initialTasks = [
  {
    id: '1',
    title: 'Complete KYC verification for Taker',
    project: 'Taker',
    projectColor: '#10B981',
    dueDate: 'April 20, 2024',
    completed: false,
    type: 'project'
  },
  {
    id: '2',
    title: 'Deploy test smart contract on Hyperdrive',
    project: 'Hyperdrive',
    projectColor: '#EC4899',
    dueDate: 'April 25, 2024',
    completed: true,
    type: 'project'
  },
  {
    id: '3',
    title: 'Participate in Bless beta testing',
    project: 'Bless',
    projectColor: '#F59E0B',
    dueDate: 'April 30, 2024',
    completed: false,
    type: 'project'
  },
  {
    id: '4',
    title: 'Stake 100 tokens in Alchemy protocol',
    project: 'Alchemy',
    projectColor: '#8B5CF6',
    dueDate: 'May 5, 2024',
    completed: false,
    type: 'project'
  },
  {
    id: '5',
    title: 'Join Discord and complete community tasks',
    project: 'Zephyr',
    projectColor: '#F59E0B',
    dueDate: 'April 22, 2024',
    completed: true,
    type: 'project'
  },
  {
    id: '6',
    title: 'Research new airdrop opportunities',
    project: null,
    projectColor: '#94A3B8',
    dueDate: 'April 18, 2024',
    completed: true,
    type: 'custom'
  },
  {
    id: '7',
    title: 'Set up hardware wallet for airdrops',
    project: null,
    projectColor: '#94A3B8',
    dueDate: 'April 23, 2024',
    completed: false,
    type: 'custom'
  },
  {
    id: '8',
    title: 'Check Twitter for project announcements',
    project: null,
    projectColor: '#94A3B8',
    dueDate: 'April 17, 2024',
    completed: true,
    type: 'daily'
  },
  {
    id: '9',
    title: 'Review portfolio performance',
    project: null,
    projectColor: '#94A3B8',
    dueDate: 'April 17, 2024',
    completed: false,
    type: 'daily'
  }
];

// Initial news data
const initialNews = [
  {
    id: '1',
    title: 'Hyperdrive Announces Mainnet Launch Date',
    content: 'Hyperdrive, the high-throughput blockchain for enterprise applications, has officially announced their mainnet launch date for May 10, 2024. The team also confirmed that early testnet participants will receive a bonus airdrop allocation.',
    source: 'Crypto Daily',
    date: 'April 15, 2024',
    category: 'Project Updates',
    image: 'assets/news/hyperdrive-news.jpg'
  },
  {
    id: '2',
    title: 'Taker DEX Completes $15M Funding Round',
    content: 'Decentralized order book exchange Taker has successfully completed a $15M funding round led by top crypto venture capital firms. The funds will be used to accelerate development and expand cross-chain capabilities ahead of their token launch in July.',
    source: 'BlockNews',
    date: 'April 12, 2024',
    category: 'Funding',
    image: 'assets/news/taker-news.jpg'
  },
  {
    id: '3',
    title: 'Bless Platform Opens Beta Registration',
    content: 'The AI-powered prediction market Bless has opened registration for their closed beta testing program. Users who participate in the beta and provide feedback will be eligible for the upcoming airdrop scheduled for August.',
    source: 'CryptoInsider',
    date: 'April 10, 2024',
    category: 'Project Updates',
    image: 'assets/news/bless-news.jpg'
  },
  {
    id: '4',
    title: 'Quantum L2 Announces Testnet Incentive Program',
    content: 'Quantum, the privacy-focused Layer 2 solution, has unveiled their testnet incentive program with a total reward pool of 5 million QTM tokens. The program will run for 6 weeks starting May 1st, with participants earning points for completing various network activities.',
    source: 'L2Beat',
    date: 'April 8, 2024',
    category: 'Airdrops',
    image: 'assets/news/quantum-news.jpg'
  },
  {
    id: '5',
    title: 'Alchemy Protocol Introduces New Yield Strategies',
    content: 'Decentralized asset management protocol Alchemy has introduced three new yield strategies for users to test on their testnet. The team has hinted that early adopters who deploy assets to these strategies will be rewarded in the upcoming token distribution.',
    source: 'DeFi Pulse',
    date: 'April 5, 2024',
    category: 'Project Updates',
    image: 'assets/news/alchemy-news.jpg'
  },
  {
    id: '6',
    title: 'Blockmesh Network Achieves 10,000 TPS in Latest Benchmark',
    content: 'The decentralized mesh network Blockmesh has achieved an impressive 10,000 transactions per second in their latest benchmark test. This performance puts it among the fastest Layer 2 solutions in development, potentially making it a strong contender in the scaling race.',
    source: 'Crypto Research',
    date: 'April 3, 2024',
    category: 'Technology',
    image: 'assets/news/blockmesh-news.jpg'
  },
  {
    id: '7',
    title: 'Fusion Protocol Announces Cross-Chain Airdrop',
    content: 'Interoperability protocol Fusion has announced an innovative cross-chain airdrop that will reward users across multiple blockchains. Eligibility will be determined by on-chain activity across Ethereum, Solana, and four other major networks.',
    source: 'AirdropAlert',
    date: 'April 1, 2024',
    category: 'Airdrops',
    image: 'assets/news/fusion-news.jpg'
  }
];

// Initial transactions data
const initialTransactions = [
  {
    id: '1',
    type: 'investment',
    project: 'Taker',
    amount: 1200,
    date: 'April 10, 2024'
  },
  {
    id: '2',
    type: 'investment',
    project: 'Hyperdrive',
    amount: 2500,
    date: 'March 25, 2024'
  },
  {
    id: '3',
    type: 'investment',
    project: 'Bless',
    amount: 800,
    date: 'March 15, 2024'
  },
  {
    id: '4',
    type: 'earning',
    project: 'Alchemy',
    amount: 350,
    date: 'April 5, 2024'
  },
  {
    id: '5',
    type: 'earning',
    project: 'Zephyr',
    amount: 180,
    date: 'March 30, 2024'
  },
  {
    id: '6',
    type: 'investment',
    project: 'Alchemy',
    amount: 1300,
    date: 'February 20, 2024'
  },
  {
    id: '7',
    type: 'earning',
    project: 'Hyperdrive',
    amount: 420,
    date: 'March 28, 2024'
  },
  {
    id: '8',
    type: 'earning',
    project: 'Taker',
    amount: 300,
    date: 'April 12, 2024'
  }
];